/** 一時ルール・派生ルールのシードデータ（仕様 §14 / §10） */
import type { BusinessRule, DerivationRule } from "../src/core/model/types";

export const businessRules: BusinessRule[] = [
  {
    id: "rule-september-inquiry",
    name: "9月限定：問い合わせ時ヒアリング強化",
    description: "9月の商談化率向上施策のため、初回接触時に3項目を必ず確認する。",
    ruleType: "temporary",
    priority: 0,
    enabled: true,
    activeFrom: "2026-09-01T00:00:00+09:00",
    activeTo: "2026-09-30T23:59:59+09:00",
    scope: {
      workflowKeys: ["inquiry-new"],
      stepRuleTags: ["hearing"],
      componentTypes: [],
      teams: [],
    },
    effects: [
      {
        type: "addChecklistItems",
        items: [
          { key: "budget", label: "予算を確認", required: true },
          { key: "timeline", label: "導入時期を確認", required: true },
          { key: "ai-experience", label: "AI導入経験を確認", required: true },
        ],
      },
      {
        type: "showNotice",
        level: "info",
        text: "9月限定ルールが適用されています（〜2026/09/30）。予算・導入時期・AI導入経験の確認が必須です。",
      },
    ],
    createdBy: "user-manager",
    createdAt: "2026-08-25T10:00:00+09:00",
  },
  {
    id: "rule-mail-double-check",
    name: "メール送信前の宛先ダブルチェック",
    description: "誤送信防止のため、メール作成時は宛先を再確認する。",
    ruleType: "department",
    priority: 10,
    enabled: true,
    activeFrom: "2026-01-01T00:00:00+09:00",
    scope: {
      workflowKeys: [],
      stepRuleTags: ["email"],
      componentTypes: [],
      teams: ["sales"],
    },
    effects: [
      {
        type: "addChecklistItems",
        items: [{ key: "recipient-check", label: "宛先アドレスを再確認", required: true }],
      },
    ],
    createdBy: "user-admin",
    createdAt: "2026-01-05T10:00:00+09:00",
  },
  {
    id: "rule-article-legal",
    name: "記事の薬機法チェック（10月まで）",
    description: "健康関連テーマの記事が増えているため、公開前に表現チェックを追加する。",
    ruleType: "temporary",
    priority: 0,
    enabled: true,
    activeFrom: "2026-08-01T00:00:00+09:00",
    activeTo: "2026-10-31T23:59:59+09:00",
    scope: {
      workflowKeys: ["article-writing"],
      stepRuleTags: ["article"],
      componentTypes: [],
      teams: ["marketing"],
    },
    effects: [
      {
        type: "showNotice",
        level: "warn",
        text: "健康・効能に関する表現を含む場合、法務確認が必要です（〜2026/10/31）。",
      },
      { type: "attachKnowledge", knowledgeIds: ["kb-legal-expression"] },
    ],
    createdBy: "user-manager",
    createdAt: "2026-07-28T10:00:00+09:00",
  },
  {
    id: "rule-expired-summer",
    name: "夏季キャンペーン対応（終了済み）",
    description: "8月の夏季キャンペーン期間中の特別対応。期間終了により自動的に無効。",
    ruleType: "temporary",
    priority: 0,
    enabled: true,
    activeFrom: "2026-08-01T00:00:00+09:00",
    activeTo: "2026-08-20T23:59:59+09:00",
    scope: {
      workflowKeys: ["inquiry-new"],
      stepRuleTags: ["hearing"],
      componentTypes: [],
      teams: [],
    },
    effects: [
      {
        type: "addChecklistItems",
        items: [{ key: "campaign-code", label: "キャンペーンコードを確認", required: true }],
      },
    ],
    createdBy: "user-manager",
    createdAt: "2026-07-20T10:00:00+09:00",
  },
];

export const derivationRules: DerivationRule[] = [
  {
    id: "dr-campaign-date-change",
    name: "キャンペーン配信日変更に伴う派生タスク",
    description: "配信終了日を変更した場合に必要となる関連対応を洗い出す。",
    enabled: true,
    priority: 100,
    trigger: {
      entityType: "campaign",
      field: "endDate",
      changeKind: "updated",
      condition: {
        op: "neq",
        left: { kind: "var", path: "change.before" },
        right: { kind: "var", path: "change.after" },
      },
    },
    scope: { workflowKeys: [], teams: ["marketing", "sales"] },
    effects: [
      {
        ref: "delivery",
        title: "配信設定の期間変更",
        description: "配信システム上の終了日を新しい日付に更新する。",
        assigneeRole: "marketing",
        impact: "direct",
        priority: "high",
        deadline: { from: "change.after", offsetDays: -10, businessDaysOnly: true },
      },
      {
        ref: "lp",
        title: "LP掲載期間の変更",
        description: "ランディングページの掲載終了日と表記を更新する。",
        assigneeRole: "marketing",
        impact: "direct",
        priority: "high",
        deadline: { from: "change.after", offsetDays: -8, businessDaysOnly: true },
      },
      {
        ref: "mail",
        title: "案内メール内容の日付確認",
        description: "配信予定のメール本文に含まれる日付表記を確認・修正する。",
        assigneeRole: "marketing",
        impact: "indirect",
        deadline: { from: "change.after", offsetDays: -6, businessDaysOnly: true },
        dependsOnRefs: ["lp"],
      },
      {
        ref: "sales-doc",
        title: "営業資料の記載日付確認",
        description: "営業が使用する資料の期間表記を確認・修正する。",
        assigneeRole: "sales",
        impact: "indirect",
        deadline: { from: "change.after", offsetDays: -5, businessDaysOnly: true },
      },
      {
        ref: "notify",
        title: "関係者への変更通知",
        description: "営業・マーケ・カスタマーサポートへ変更内容を周知する。",
        assigneeRole: "sales",
        impact: "indirect",
        deadline: { from: "change.after", offsetDays: -3, businessDaysOnly: true },
        dependsOnRefs: ["delivery", "lp"],
      },
      {
        ref: "contract",
        title: "契約期間との整合を確認",
        description: "延長が契約範囲内かを確認する。範囲外の場合は追加の承認が必要。",
        assigneeRole: "sales",
        impact: "check",
        priority: "high",
        deadline: { from: "change.after", offsetDays: -12, businessDaysOnly: true },
      },
    ],
  },
  {
    id: "dr-article-publish-date",
    name: "記事公開日変更に伴う派生タスク",
    description: "記事の公開予定日を変更した場合の関連対応。",
    enabled: true,
    priority: 90,
    trigger: { entityType: "article", field: "publishDate", changeKind: "updated" },
    scope: { workflowKeys: ["article-writing"], teams: ["marketing"] },
    effects: [
      {
        ref: "sns",
        title: "SNS投稿予約の変更",
        assigneeRole: "marketing",
        impact: "direct",
        deadline: { from: "change.after", offsetDays: -2, businessDaysOnly: true },
      },
      {
        ref: "mailmagazine",
        title: "メルマガ掲載号の調整",
        assigneeRole: "marketing",
        impact: "indirect",
        deadline: { from: "change.after", offsetDays: -3, businessDaysOnly: true },
        dependsOnRefs: ["sns"],
      },
      {
        ref: "writer",
        title: "執筆者への納期変更連絡",
        assigneeRole: "marketing",
        impact: "check",
        deadline: { from: "change.after", offsetDays: -7, businessDaysOnly: true },
      },
    ],
  },
];
