/**
 * 業務フロー定義のシードデータ。
 * これらは「データ」であり、コンポーネント側に手順を書かない。
 * 将来 DB へ移す際は、この配列をそのままレコードに置き換える。
 */
import type { WorkflowDefinition } from "../src/core/model/types";

export const workflows: WorkflowDefinition[] = [
  // -------------------------------------------------------------------------
  // 1. 新規問い合わせ対応（条件分岐あり：既存顧客／新規顧客、企業規模）
  // -------------------------------------------------------------------------
  {
    key: "inquiry-new",
    version: 1,
    status: "published",
    name: "新規問い合わせ対応",
    description: "Webフォームからの新規問い合わせに対する初期対応。24時間以内の一次返信が目標。",
    category: "営業",
    audience: { roles: ["executor"], teams: ["sales", "inside-sales"] },
    ruleTags: ["inquiry", "sales"],
    derivationRuleIds: [],
    estimatedMinutes: 75,
    updatedAt: "2026-08-01T09:00:00+09:00",
    deadlineRule: { from: "run.startedAt", offsetHours: 24 },
    completionPolicy: { requireAllRequiredSteps: true },
    variables: [
      { key: "customerId", label: "顧客", type: "reference", entity: "customer", required: true },
      { key: "customerType", label: "顧客区分", type: "string", required: true,
        // 顧客マスタの取引実績から初期値を導く。ユーザーは変更できる
        derivedFrom: { entity: "customer", field: "isExisting", map: { true: "existing", false: "new" } } },
      { key: "employeeCount", label: "従業員規模", type: "number", required: false },
      { key: "inquiryKind", label: "問い合わせ種別", type: "string", required: true },
      { key: "service", label: "提案サービス", type: "string", required: true },
    ],
    steps: [
      {
        key: "receive", title: "問い合わせ受信", required: true,
        guidance: "受信した問い合わせ内容を確認し、対応を開始します。",
        componentType: "customer-view", estimatedMinutes: 5,
        config: { showFields: ["company", "contact", "industry", "history"] },
        knowledgeRefs: ["kb-inquiry-sla"], ruleTags: ["inquiry"],
      },
      {
        key: "classify-inquiry", title: "問い合わせ内容の分類", required: true,
        guidance: "受信した問い合わせが何についてのものかを記録します。以降の判断の前提になります。",
        componentType: "select", estimatedMinutes: 3,
        config: {
          fields: [
            { key: "inquiryKind", label: "問い合わせ種別", required: true,
              options: [
                { value: "service", label: "サービス内容の問い合わせ" },
                { value: "estimate", label: "見積り依頼" },
                { value: "material", label: "資料請求" },
                { value: "support", label: "既存サービスのサポート" },
                { value: "other", label: "その他" },
              ] },
          ],
        },
        knowledgeRefs: ["kb-inquiry-sla"], ruleTags: ["inquiry"],
      },
      {
        key: "confirm-customer", title: "顧客情報確認", required: true,
        guidance: "既存顧客か新規顧客かを判定し、過去の取引履歴を確認します。",
        componentType: "select", estimatedMinutes: 5,
        config: {
          fields: [
            { key: "customerType", label: "顧客区分", required: true,
              options: [
                { value: "existing", label: "既存顧客" },
                { value: "new", label: "新規顧客" },
              ] },
            { key: "employeeCount", label: "従業員規模", required: true,
              options: [
                { value: 50, label: "〜50名" },
                { value: 300, label: "51〜300名" },
                { value: 1000, label: "301名以上" },
              ] },
          ],
        },
        knowledgeRefs: ["kb-customer-check"], ruleTags: ["inquiry", "customer"],
      },
      {
        key: "branch-customer", title: "顧客区分による分岐", required: false,
        guidance: "顧客区分に応じて次の対応を切り替えます。",
        componentType: "branch", config: {},
      },
      {
        key: "check-history", title: "既存取引の確認", required: false,
        guidance: "既存顧客のため、進行中の案件・過去の提案内容を確認します。",
        componentType: "checklist", estimatedMinutes: 10,
        config: {
          items: [
            { key: "past-deals", label: "過去の提案内容を確認", required: true },
            { key: "open-issues", label: "未解決の課題がないか確認", required: true },
            { key: "owner", label: "既存担当者に連携", required: false },
          ],
        },
        knowledgeRefs: ["kb-existing-customer"], ruleTags: ["inquiry", "customer"],
      },
      {
        key: "required-info", title: "必要情報確認", required: true,
        guidance: "提案に必要な情報が揃っているかを確認します。不足があればヒアリングで補います。",
        componentType: "checklist", estimatedMinutes: 10,
        config: {
          items: [
            { key: "purpose", label: "問い合わせの目的", required: true },
            { key: "target", label: "対象部門・対象者", required: true },
            { key: "deadline", label: "検討スケジュール", required: false },
          ],
        },
        ruleTags: ["inquiry"],
      },
      {
        key: "hearing", title: "ヒアリング", required: true,
        guidance: "顧客の課題・規模・決裁者を確認します。期間限定ルールがある場合は追加項目が表示されます。",
        componentType: "checklist", estimatedMinutes: 20,
        config: {
          items: [
            { key: "issue", label: "課題", required: true },
            { key: "scale", label: "対象規模", required: true },
            { key: "decider", label: "決裁者", required: false },
          ],
        },
        // ↓ 9月限定ルールはこのタグを見て刺さる
        ruleTags: ["inquiry", "hearing"],
        knowledgeRefs: ["kb-hearing-guide"],
        // 業務全体のSLAが24時間なので、全体期限の1日前（＝開始時刻）にすると
        // 開始した瞬間に期限超過になる。受付から4時間以内を目安にする。
        deadlineRule: { from: "run.startedAt", offsetHours: 4 },
      },
      {
        key: "select-service", title: "企業・サービス選定", required: true,
        guidance: "ヒアリング結果に基づき、提案するサービスを選定します。",
        componentType: "select", estimatedMinutes: 10,
        config: {
          fields: [
            { key: "service", label: "提案サービス", required: true,
              options: [
                { value: "ai-consulting", label: "AI導入コンサルティング" },
                { value: "dev", label: "受託開発" },
                { value: "training", label: "社内研修" },
              ] },
          ],
        },
        knowledgeRefs: ["kb-service-matrix"], ruleTags: ["inquiry"],
      },
      {
        key: "branch-scale", title: "規模による分岐", required: false,
        guidance: "企業規模により、上長承認の要否を判定します。",
        componentType: "branch", config: {},
      },
      {
        key: "approval", title: "上長承認", required: false,
        guidance: "大企業案件のため、提案内容について上長の承認を得ます。",
        componentType: "approval", estimatedMinutes: 5,
        config: { approverRole: "manager" },
        ruleTags: ["approval"],
      },
      {
        key: "compose-email", title: "メール作成", required: true,
        guidance: "テンプレートを選び、顧客情報を差し込んで返信メールを作成します。",
        componentType: "email-compose", estimatedMinutes: 15,
        config: { templateId: "tpl-inquiry-reply", aiAssist: true },
        ruleTags: ["email"], knowledgeRefs: ["kb-mail-tone"],
      },
      {
        key: "send", title: "送信", required: true,
        guidance: "内容を最終確認して送信します。差し込み値の欠損がないか確認してください。",
        componentType: "approval", estimatedMinutes: 3,
        config: { selfConfirm: true, reviewStepKey: "compose-email", confirmLabel: "内容を確認して送信する" },
        ruleTags: ["email"],
      },
      {
        key: "create-tasks", title: "フォローアップタスク作成", required: true,
        guidance: "次のアクションをタスクとして登録します。",
        componentType: "task-create", estimatedMinutes: 5,
        config: {
          templates: [
            { title: "初回提案資料の準備", offsetDays: 2, businessDaysOnly: true, priority: "high" },
            { title: "1週間後フォロー連絡", offsetDays: 5, businessDaysOnly: true, priority: "normal" },
          ],
        },
        ruleTags: ["task"],
      },
      {
        key: "done", title: "完了", required: true,
        guidance: "対応内容を記録して業務を終了します。",
        componentType: "complete", config: {},
      },
    ],
    edges: [
      { from: "receive", to: "classify-inquiry", priority: 1 },
      { from: "classify-inquiry", to: "confirm-customer", priority: 1 },
      { from: "confirm-customer", to: "branch-customer", priority: 1 },
      { from: "branch-customer", to: "check-history", priority: 1, label: "既存顧客",
        condition: { op: "eq", left: { kind: "var", path: "context.customerType" }, right: { kind: "literal", value: "existing" } } },
      { from: "branch-customer", to: "required-info", priority: 2, label: "新規顧客" },
      { from: "check-history", to: "required-info", priority: 1 },
      { from: "required-info", to: "hearing", priority: 1 },
      { from: "hearing", to: "select-service", priority: 1 },
      { from: "select-service", to: "branch-scale", priority: 1 },
      { from: "branch-scale", to: "approval", priority: 1, label: "301名以上（要承認）",
        condition: { op: "gte", left: { kind: "var", path: "context.employeeCount" }, right: { kind: "literal", value: 1000 } } },
      { from: "branch-scale", to: "compose-email", priority: 2, label: "300名以下" },
      { from: "approval", to: "compose-email", priority: 1 },
      { from: "compose-email", to: "send", priority: 1 },
      { from: "send", to: "create-tasks", priority: 1 },
      { from: "create-tasks", to: "done", priority: 1 },
    ],
  },

  // -------------------------------------------------------------------------
  // 2. CV後フォロー
  // -------------------------------------------------------------------------
  {
    key: "post-cv",
    version: 1,
    status: "published",
    name: "CV後フォロー",
    description: "資料請求・問い合わせ完了（CV）直後のフォロー対応。",
    category: "営業",
    audience: { roles: ["executor"], teams: ["sales"] },
    ruleTags: ["cv", "sales"],
    derivationRuleIds: [],
    estimatedMinutes: 45,
    updatedAt: "2026-08-01T09:00:00+09:00",
    deadlineRule: { from: "run.startedAt", offsetHours: 48 },
    completionPolicy: { requireAllRequiredSteps: true },
    variables: [
      { key: "customerId", label: "顧客", type: "reference", entity: "customer", required: true },
      { key: "followDate", label: "フォロー予定日", type: "date", required: true },
    ],
    steps: [
      { key: "cv", title: "CV確認", required: true,
        guidance: "コンバージョンした顧客の情報と、ダウンロードされた資料を確認します。",
        componentType: "customer-view", estimatedMinutes: 5,
        config: { showFields: ["company", "contact", "history"] },
        ruleTags: ["cv"] },
      { key: "thanks-mail", title: "お礼メール作成", required: true,
        guidance: "資料請求へのお礼と、次のご案内を含むメールを作成します。",
        componentType: "email-compose", estimatedMinutes: 10,
        config: { templateId: "tpl-cv-thanks", aiAssist: true },
        ruleTags: ["email"], knowledgeRefs: ["kb-mail-tone"] },
      { key: "send-material", title: "資料送付", required: true,
        guidance: "顧客の関心に合わせた追加資料を選んで送付します。",
        componentType: "checklist", estimatedMinutes: 10,
        config: { items: [
          { key: "select-doc", label: "送付資料を選定", required: true },
          { key: "check-version", label: "資料が最新版か確認", required: true },
        ] },
        knowledgeRefs: ["kb-material-list"], ruleTags: ["document"] },
      { key: "set-follow", title: "フォロー日設定", required: true,
        guidance: "次回フォローの日付を決めます。標準は1週間後です。",
        componentType: "input", estimatedMinutes: 3,
        config: { fields: [{ key: "followDate", label: "フォロー予定日", type: "date", required: true }] },
        ruleTags: ["task"] },
      { key: "calendar", title: "Calendar登録", required: true,
        guidance: "フォロー予定をカレンダーに登録します。",
        componentType: "calendar-create", estimatedMinutes: 3,
        config: { titleTemplate: "{{customer.name}} フォロー連絡", dateVar: "followDate" },
        ruleTags: ["calendar"] },
      { key: "done", title: "完了", required: true,
        guidance: "フォロー体制の設定が完了しました。",
        componentType: "complete", config: {} },
    ],
    edges: [
      { from: "cv", to: "thanks-mail", priority: 1 },
      { from: "thanks-mail", to: "send-material", priority: 1 },
      { from: "send-material", to: "set-follow", priority: 1 },
      { from: "set-follow", to: "calendar", priority: 1 },
      { from: "calendar", to: "done", priority: 1 },
    ],
  },

  // -------------------------------------------------------------------------
  // 3. 記事作成（並列STEPと合流あり）
  // -------------------------------------------------------------------------
  {
    key: "article-writing",
    version: 1,
    status: "published",
    name: "記事作成",
    description: "オウンドメディア記事の企画から公開までの制作フロー。",
    category: "マーケティング",
    audience: { roles: ["executor"], teams: ["marketing"] },
    ruleTags: ["article", "marketing"],
    derivationRuleIds: [],
    estimatedMinutes: 300,
    updatedAt: "2026-08-01T09:00:00+09:00",
    deadlineRule: { from: "run.startedAt", offsetDays: 14 },
    completionPolicy: { requireAllRequiredSteps: true },
    variables: [
      { key: "theme", label: "テーマ", type: "string", required: true },
      { key: "articleType", label: "記事種別", type: "string", required: true },
    ],
    steps: [
      { key: "plan", title: "企画・テーマ決定", required: true,
        guidance: "記事のテーマ・想定読者・獲得したい検索キーワードを決めます。",
        componentType: "input", estimatedMinutes: 30,
        config: { fields: [
          { key: "theme", label: "テーマ", required: true },
          { key: "audience", label: "想定読者", required: true },
          { key: "keyword", label: "対策キーワード", required: false },
        ] },
        knowledgeRefs: ["kb-article-policy"], ruleTags: ["article"] },
      { key: "select-type", title: "記事種別の選択", required: true,
        guidance: "記事の種別により、以降の制作フローが変わります。",
        componentType: "select", estimatedMinutes: 5,
        config: { fields: [{ key: "articleType", label: "記事種別", required: true, options: [
          { value: "interview", label: "インタビュー記事" },
          { value: "column", label: "コラム記事" },
        ] }] },
        ruleTags: ["article"] },
      { key: "branch-type", title: "種別による分岐", required: false,
        guidance: "記事種別に応じて取材の要否が変わります。",
        componentType: "branch", config: {} },
      { key: "interview", title: "取材実施", required: false,
        guidance: "インタビュー記事のため、取材のアポイントと実施を行います。",
        componentType: "checklist", estimatedMinutes: 90,
        config: { items: [
          { key: "appoint", label: "取材アポイント取得", required: true },
          { key: "questions", label: "質問票の事前送付", required: true },
          { key: "record", label: "取材実施・録音", required: true },
        ] },
        knowledgeRefs: ["kb-interview-guide"], ruleTags: ["article"] },
      { key: "draft", title: "原稿作成", required: true,
        guidance: "構成に沿って本文を執筆します。",
        componentType: "document-compose", estimatedMinutes: 120,
        config: { templateId: "tpl-article", aiAssist: true },
        ruleTags: ["document", "article"], knowledgeRefs: ["kb-article-policy"] },
      { key: "prepare-image", title: "画像手配", required: true,
        guidance: "アイキャッチ画像と本文中の図版を手配します。原稿作成と並行して進められます。",
        componentType: "checklist", estimatedMinutes: 40,
        config: { items: [
          { key: "eyecatch", label: "アイキャッチ作成", required: true },
          { key: "rights", label: "画像の利用権を確認", required: true },
        ] },
        ruleTags: ["article"] },
      { key: "review", title: "校正・レビュー", required: true,
        guidance: "原稿と画像が揃ったら、校正とレビューを行います。",
        componentType: "checklist", estimatedMinutes: 30,
        config: { items: [
          { key: "proofread", label: "誤字脱字チェック", required: true },
          { key: "fact", label: "ファクトチェック", required: true },
          { key: "legal", label: "表現の適法性確認", required: true },
        ] },
        knowledgeRefs: ["kb-article-policy"], ruleTags: ["article"] },
      { key: "publish", title: "公開", required: true,
        guidance: "公開設定を行い、記事を公開します。",
        componentType: "checklist", estimatedMinutes: 15,
        config: { items: [
          { key: "meta", label: "メタ情報を設定", required: true },
          { key: "publish", label: "公開", required: true },
        ] },
        ruleTags: ["article"] },
      { key: "done", title: "完了", required: true,
        guidance: "記事の公開が完了しました。",
        componentType: "complete", config: {} },
    ],
    edges: [
      { from: "plan", to: "select-type", priority: 1 },
      { from: "select-type", to: "branch-type", priority: 1 },
      { from: "branch-type", to: "interview", priority: 1, label: "インタビュー記事",
        condition: { op: "eq", left: { kind: "var", path: "context.articleType" }, right: { kind: "literal", value: "interview" } } },
      { from: "branch-type", to: "draft", priority: 2, label: "コラム記事" },
      { from: "branch-type", to: "prepare-image", priority: 3, label: "並行して画像手配" },
      { from: "interview", to: "draft", priority: 1 },
      // 原稿と画像が両方そろってからレビューへ（合流）
      { from: "draft", to: "review", priority: 1, joinPolicy: "all" },
      { from: "prepare-image", to: "review", priority: 1, joinPolicy: "all" },
      { from: "review", to: "publish", priority: 1 },
      { from: "publish", to: "done", priority: 1 },
    ],
  },

  // -------------------------------------------------------------------------
  // 4. 企業リサーチ
  // -------------------------------------------------------------------------
  {
    key: "company-research",
    version: 1,
    status: "published",
    name: "企業リサーチ",
    description: "条件に合致する企業を検索し、営業対象を選定する。",
    category: "営業",
    audience: { roles: ["executor"], teams: ["sales", "inside-sales"] },
    ruleTags: ["research", "sales"],
    derivationRuleIds: [],
    estimatedMinutes: 120,
    updatedAt: "2026-08-01T09:00:00+09:00",
    deadlineRule: { from: "run.startedAt", offsetDays: 5 },
    completionPolicy: { requireAllRequiredSteps: true },
    variables: [
      { key: "conditions", label: "検索条件", type: "object", required: true },
      { key: "selectedCompanies", label: "選定企業", type: "object", required: true },
    ],
    steps: [
      { key: "conditions", title: "条件入力", required: true,
        guidance: "検索する企業の条件を指定します。",
        componentType: "input", estimatedMinutes: 10,
        config: { fields: [
          { key: "industry", label: "業界", required: true },
          { key: "region", label: "地域", required: false },
          { key: "targetCount", label: "選定目標社数", type: "number", required: true },
        ] },
        ruleTags: ["company-search", "research"] },
      { key: "search", title: "企業検索", required: true,
        guidance: "条件に合致する企業を検索します。",
        componentType: "company-search", estimatedMinutes: 20,
        config: {},
        ruleTags: ["company-search"], knowledgeRefs: ["kb-target-criteria"] },
      { key: "select", title: "候補表示・人間による選定", required: true,
        guidance: "候補企業から営業対象を選定します。選定理由を必ず記録してください。最終判断は人が行います。",
        componentType: "company-select", estimatedMinutes: 40,
        config: { requireReason: true },
        ruleTags: ["company-search"], knowledgeRefs: ["kb-target-criteria"] },
      { key: "register", title: "企業登録", required: true,
        guidance: "選定した企業を顧客マスタに登録します。",
        componentType: "checklist", estimatedMinutes: 15,
        config: { items: [
          { key: "dup", label: "既存顧客との重複を確認", required: true },
          { key: "register", label: "マスタへ登録", required: true },
        ] },
        ruleTags: ["research"] },
      { key: "compose-email", title: "アプローチメール作成", required: true,
        guidance: "選定した企業へ送るアプローチメールを作成します。",
        componentType: "email-compose", estimatedMinutes: 25,
        config: { templateId: "tpl-approach", aiAssist: true },
        ruleTags: ["email"] },
      { key: "create-tasks", title: "タスク作成", required: true,
        guidance: "各企業へのアプローチをタスク化します。",
        componentType: "task-create", estimatedMinutes: 10,
        config: { templates: [{ title: "アプローチ結果の記録", offsetDays: 5, priority: "normal" }] },
        ruleTags: ["task"] },
      { key: "done", title: "完了", required: true,
        guidance: "企業リサーチが完了しました。",
        componentType: "complete", config: {} },
    ],
    edges: [
      { from: "conditions", to: "search", priority: 1 },
      { from: "search", to: "select", priority: 1 },
      { from: "select", to: "register", priority: 1 },
      { from: "register", to: "compose-email", priority: 1 },
      { from: "compose-email", to: "create-tasks", priority: 1 },
      { from: "create-tasks", to: "done", priority: 1 },
    ],
  },

  // -------------------------------------------------------------------------
  // 5. メール作成（単体業務）
  // -------------------------------------------------------------------------
  {
    key: "email-standalone",
    version: 1,
    status: "published",
    name: "メール作成",
    description: "テンプレートを使った単発のメール作成業務。",
    category: "共通",
    audience: { roles: ["executor"], teams: [] },
    ruleTags: ["email"],
    derivationRuleIds: [],
    estimatedMinutes: 25,
    updatedAt: "2026-08-01T09:00:00+09:00",
    deadlineRule: { from: "run.startedAt", offsetHours: 24 },
    completionPolicy: { requireAllRequiredSteps: true },
    variables: [
      { key: "customerId", label: "宛先", type: "reference", entity: "customer", required: true },
    ],
    steps: [
      { key: "pick-target", title: "宛先確認", required: true,
        guidance: "送信先の顧客情報を確認します。",
        componentType: "customer-view", estimatedMinutes: 5,
        config: { showFields: ["company", "contact", "history"] },
        ruleTags: ["email", "customer"] },
      { key: "compose", title: "メール作成", required: true,
        guidance: "テンプレートを選び、内容を作成します。",
        componentType: "email-compose", estimatedMinutes: 15,
        config: { templateId: "tpl-approach", aiAssist: true },
        ruleTags: ["email"], knowledgeRefs: ["kb-mail-tone"] },
      { key: "send", title: "送信", required: true,
        guidance: "内容を最終確認して送信します。",
        componentType: "approval", estimatedMinutes: 3,
        config: { selfConfirm: true, reviewStepKey: "compose", confirmLabel: "内容を確認して送信する" },
        ruleTags: ["email"] },
      { key: "done", title: "完了", required: true,
        guidance: "メール送信が完了しました。",
        componentType: "complete", config: {} },
    ],
    edges: [
      { from: "pick-target", to: "compose", priority: 1 },
      { from: "compose", to: "send", priority: 1 },
      { from: "send", to: "done", priority: 1 },
    ],
  },
];
